### ISSUE TITLE
add quick search filter to mensa multiselect dialog

### ISSUE THREAD

**Issue by krichter722** [mswart/pyopenmensa#7]
in order to be able to deal with different naming styles (start with city, "Mensa", or university name)

**Comment by mswart** [comment]
Please describe your issue a bit more. I am not sure what you mean. My main issue is: pyopenmensa is only a library for parser authors. It has no interaction with users and nothing like a multiselect dialog.

Could it be you are talking about [the OpenMensa project itself (website, API ...)](https://github.com/openmensa/openmensa) or a OpenMensa client app like [the Android OpenMensa App](https://github.com/domoritz/open-mensa-android).

To reduce the number of name variants I have opened openmensa/openmensa#9. But due to the current work load is most likely a long term change.

**Comment by krichter722** [comment]
see https://github.com/domoritz/open-mensa-android/issues/29

**Comment by mswart** [comment]
thx for clarification.
